; PlatformIO Project Configuration File
[platformio]
src_dir = applications/
include_dir = drivers/

; Build options: build_flags, lib_deps, extra_scripts
[env]
# Move these here so ALL environments inherit them
platform = espressif32
board = esp32dev
framework = espidf
build_flags = -std=c++2a
lib_deps =
    https://github.com/martinmoene/ring-span-lite.git
check_tool = clangtidy, cppcheck
check_flags =
  clangtidy: --config-file=${project_dir}/.clang-tidy --header-filter=${project_dir}/drivers/.*
# Tell ESP-IDF to look at demos as a potential component source
board_build.extra_components = demos

# baudrate parameter
upload_speed=115200

; Environments-specific for application and demo builds
[env:esp32dev]
build_src_filter = +<*> +<**/*.cppm>

; Building demo for setting output pin
[env:output_pin]
build_src_filter = +<../demos/output_pin.cpp>

[env:uart]
build_src_filter = +<../demos/uart.cpp>
