[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
lib_deps =
    https://github.com/martinmoene/ring-span-lite.git
check_tool = clangtidy, cppcheck
check_flags =
  clangtidy: --config-file=${project_dir}/.clang-tidy --header-filter=${project_dir}/drivers/.*
build_src_filter = +<*> +<**/*.cppm>

[platformio]
# Change the directories here
src_dir = applications/
include_dir = drivers/

[env]
build_flags =
    -std=c++2a